[phases.setup]
nixPkgs = ['nodejs', 'npm', 'chromium']

[phases.install]
cmds = ['npm ci', 'npm run build']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'npm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/nix/store/*/bin/chromium' 